[DOM-48532] Domino Cost App
cerebrotech/app-costs-dashboard pull request #1
Opened 2023-08-01 12:06 UTC by ddl-juan-cistaro

2023-08-01 14:26 UTC, ddl-olsonJD requested changes

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +This describes the how to setup and run `Domino Cost App`.
This repo describes how to setup and run the `Domino Cost App` along with a Domino Cost App that can be used as a starting point.

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +To deploy Domino Cost app we need a project to be a home for it. We recomend creating a specific project for it.
The Domino Cost app requires a project to be launched from.

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +2. Select a name and visibility that you prefer for this project.
Select a name and visibility for this project.

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +3. Navigate to the `App` section in the sidebar of the project and select a name for the Domino Cost App that you prefer and you can easily identify. The standar environment and the smaller harware t
of the project and `add a title` for the Domino Cost App that
The `standard` environment

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +4. After publishing it, we'll be redirected to the `App Status` pages.
`you`'ll be redirected

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +Now that we have a dedicated project to host our app. In order to publish it follow this steps:
Once a dedicated project has been created or selected to host our app.

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +   We'll have to wait until the status changes to `running`.
Wait until the status changes to `running`.

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +   In this moment all the requeriments for the Domino Cost App to run will start to be installed and it will take a moment until the app is actually running.
It will take a moment for the dependencies to install, and the Domino Cost App to start running.

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +  If we want to verify the proper set up of our up will be able to do that from the app's user output. To be able to access them, just follow the next steps:
To verify that the app is properly setup, you can check the app's user output. To access them, follow the next steps:

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +  2. Click on the las newest version in the table and a side bar will be display in the right of the screen.
Click on the newest version in the

2023-08-01 14:26 UTC, ddl-olsonJD commented on README.md
> +After a moment that the status app is status is set as `running` you'll be able to access the app by clicking in the button `View App` in the UI.
After a moment that the app's status will be set to `running` and you will be able to access the app by clicking on the button `View App` in the UI.

2023-08-01 14:26 UTC, ddl-olsonJD commented on app/domino_cost.py
> +#breakdown_choice = sl.reactive(breakdown_options[0])
remove comment if not needed.

2023-08-01 14:26 UTC, ddl-olsonJD commented on app/domino_cost.py
> +# (lefthand chart), we want to change the breakdown to something else
What does this mean?

2023-08-01 14:42 UTC, ddl-juan-cistaro commented on app/domino_cost.py
> +# (lefthand chart), we want to change the breakdown to something else
That was an existing comment of the previous code. Sorry for that

2023-08-02 12:22 UTC, ddl-olsonJD approved these changes
Please see the change requests
not sure about the _func_names as these. functions will not be called outside of this file,

2023-08-02 13:24 UTC, merged