DOM-49403 - Domino Cost Dashboard crashes after applying validation for params
cerebrotech/app-costs-dashboard pull request #2
Opened 2023-08-17 13:09 UTC by ddl-juan-cistaro

2023-08-18 14:58 UTC, ddl-juan-cistaro commented on app/domino_cost.py
> -    # "Execution Type": "dominodatalab_com_workload_type",
This was commented in the original implementation, so It's removed to clean up the code

2023-08-18 14:59 UTC, ddl-juan-cistaro commented on app/domino_cost.py
> -# TODO: This should be replaced with real values
These are not real values, we're using only these mock ones, and we don't have a definition for a functionality like this so it's removed to try to avoid confusion to the user

2023-08-18 15:01 UTC, ddl-juan-cistaro commented on app/domino_cost.py
> -            "label:dominodatalab_com_workload_id,"
Workload_id is not a valid param and we still don't have any param identified that we should be using here, so it's removed. After some research this query can be revisited and improved to add more granularity.

2023-08-18 15:02 UTC, ddl-juan-cistaro commented on app/domino_cost.py
> -                        {
This "Overflow cos" was based on mocked values, so it's removed to avoid any confusion to the user.

2023-08-23 14:57 UTC, ddl-olsonJD requested changes

2023-08-23 14:57 UTC, ddl-olsonJD commented on app/domino_cost.py
> +        workload_type, username, project_id = costData["name"].split("/")
Does this need to be duplicated?

2023-08-23 15:07 UTC, ddl-juan-cistaro commented on app/domino_cost.py
> +        workload_type, username, project_id = costData["name"].split("/")
My bad, sorry! Will remove it.

2023-08-25 15:20 UTC, ddl-olsonJD approved these changes

2023-08-25 15:21 UTC, merged